name: Daily Interview Blast

on:
  schedule:
    - cron: "0 12 * * *"   # Runs every day at 5:30 PM IST
  workflow_dispatch:

jobs:
  run-blast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create finploy_env.json
        env:
          DATA: ${{ secrets.FINPLOY_ENV }}
        run: |
          echo "$DATA" > finploy_env.json

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas gspread google-auth requests openpyxl

      - name: Print UTC time (debug)
        run: |
          echo "Current UTC Time:"
          date -u

      - name: Run script
        run: |
          echo "Running single_script.py at 5:30 PM IST (12:00 UTC)"
          python3 single_script.py
